name: "Report an bug in various Windows builds"
description: Describe an bug in various Windows builds and suggest how to make it better.
title: "[bug] [severe/moderate] [vm/host] \"Quoted bug in Windows/software\""
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to file a translation issue!  
        Please make sure to give it a correct title. e.g. _[bug] [severe] [vm] Windows 11 throws into UNSUPPORTED_PROCESSOR_
  - type: dropdown
    id: store-origin
    attributes:
      label: Modded or vanilla
      description: Which is the type of this OS?
      options:
        - "Modded"
        - "Vanilla or Original"
    validations:
      required: true
  - type: dropdown
    id: machine-vm
    attributes:
      label: Machine
      description: Which the machine type you're sending?
      options:
        - "VM or Virtual"
        - "Phisycal or Host"
    validations:
      required: true
  - type: input
    id: versions
    attributes:
      label: Affected version(s)
      description: Which version of Windows can this issue be found in?
      placeholder: e.g. Windows 11 build 22598 or 22000.51
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Please include/paste a screenshot of the BSoD/some error in the field below.
      placeholder: The less cropping the better so we can figure out exactly where this issue is located.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe why the machine that is not working/something is wrong.
      placeholder: e.g. What happened to my PC?!?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Suggest a bugfix and briefly explain what it improves. If the text in question had a fix in Windows/my softwares/other software in the past please mention the last correct version you remember using.
      placeholder: e.g. "This app can't open/Your PC ran into a problem" The meaning of the action is clearer and sheds the bug/severe bug impression.
    validations:
      required: true
